# Generated by Django 5.0.4 on 2024-05-08 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_criteriabycontrol_roadcontrol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.CharField(max_length=255, verbose_name='Montant')),
                ('paid', models.BooleanField(default=False, verbose_name='Payé')),
                ('road_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.roadcontrol')),
            ],
            options={
                'verbose_name': 'Amende',
                'verbose_name_plural': 'Amendes',
            },
        ),
    ]
